compatibility_date = "2022-09-19"
main = "src/index.ts"
name = "workers-demo-server"

[durable_objects]
bindings = [{name = "ROOM", class_name = "Room"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]

[dev]
ip = "127.0.0.1"
